### ISSUE TITLE
Equipment sprites are different colours from inventory sprites despite being clones

### ISSUE THREAD

**Issue by L-o-ng** [Into-The-Maze/itm-beta#17]
Even the colours are the same i cant figure this out

**Comment by Jomlom** [comment]
is this because of the outline to the inventory has that translucent dark layer over it

**Comment by Jomlom** [comment]
pulled and icwym now 
strange
we'll find out why

**Comment by L-o-ng** [comment]
OPTICAL ILLUSION - inventory grid is different but can be easily fixed by adding a sorting layer
