### ISSUE TITLE
lighting kinda glitchy

### ISSUE THREAD

**Issue by Jomlom** [Into-The-Maze/itm-beta#19]
in certain seemingly random places you can see through walls with vision and shadows stop working

**Comment by Jomlom** [comment]
also bad performance lol

**Comment by L-o-ng** [comment]
appears to only happen around the edges of the maze asw, haven't seen it happen in the centre of the maze yet.

**Comment by L-o-ng** [comment]
Not too sure how the fov is created but might be an issue with raycasts slipping between maze wall blocks, causing the fov to be much larger than intended?

**Comment by Jomlom** [comment]
if it is all the overlaps I can probably fix with relative ease

**Comment by Jomlom** [comment]
fixed
