### ISSUE TITLE
Fog broken - see desc.

### ISSUE THREAD

**Issue by L-o-ng** [Into-The-Maze/itm-beta#25]
There isnt anything i can find to pass into InstantiateMaze, so for now i commented out the fog related code. There was a volume thing so i passed that into the script but i dont know if that needed configuring or anything.
![image](https://user-images.githubusercontent.com/84541379/222904013-293e0f40-9c45-40bb-808a-989a6271ee7c.png)
So make sure you take this out if you need to.

**Comment by Jomlom** [comment]
idk if I referenced them in play mode so they didn't save? but I can fix it soon as I'm at my pc

**Comment by Jomlom** [comment]
easy fixed
